[package]
name = "scuba"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "MIT OR Apache-2.0"
include = ["src/**/*.rs"]

[dependencies]
scuba_sample = { path = "../scuba_sample", version = "0.1.0" }
