[package]
name = "sql01"
version = "0.1.0"
authors = ["Facebook <opensource+rust-shed@fb.com>"]
edition = "2018"
description = "Crate for accessing sql databases"
readme = "../../../README.md"
repository = "https://github.com/facebookexperimental/rust-shed/"
license = "MIT OR Apache-2.0"

[lib]
path = "lib.rs"

[dependencies]
anyhow = "1.0"
cloned = { version = "0.1.0", path = "../../cloned" }
failure = "0.1"
failure_ext = { version = "0.1.0", path = "../../failure_ext" }
futures = "0.1.30"
futures-util = "0.3.7"
futures_ext = { package = "futures_01_ext", version = "0.1.0", path = "../../futures_01_ext" }
mysql_async = "0.23"
rusqlite = { version = "0.23", features = ["blob"] }
sql_common = { version = "0.1.0", path = "../common" }

[dev-dependencies]
fbinit-tokio-02 = { version = "0.1.0", path = "../../fbinit/fbinit-tokio-02" }
sql_tests_lib01 = { version = "0.1.0", path = "../queries01_tests" }
