[package]
name = "sql"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "MIT OR Apache-2.0"
include = ["src/**/*.rs"]

[dependencies]
failure_ext = { path = "../failure_ext" }
futures_ext = { path = "../futures_ext" }
sql_common = { path = "common" }
anyhow = "1.0"
failure = "0.1"
futures = "0.1"
mysql_async = { version = "0.23" }
rusqlite = { version = "0.23", features = ["bundled"] }

[dev-dependencies]
sql_tests_lib = { path = "tests_lib" }
