[package]
name = "sql"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/**/*.rs"]

[dependencies]
failure_ext = { path = "../failure_ext" }
futures_ext = { path = "../futures_ext" }
sql_common = { path = "common" }
anyhow = "1.0"
failure = "0.1"
futures = "0.1"
mysql_async = { version="0.20", features=["ssl"] }
rusqlite = { version = "0.21", features = ["bundled"] }

[dev-dependencies]
sql_tests_lib = { path = "tests_lib" }
