[package]
name = "time_ext"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "MIT OR Apache-2.0"
include = ["src/**/*.rs"]

[dependencies]
anyhow = "1.0"
quickcheck = "0.9"
thiserror = "1.0"
