[package]
name = "slog_stats"
edition = "2018"
version = "0.1.0"
authors = ['Facebook', 'Daniel Xu <dlxu@fb.com>']
license = "MIT OR Apache-2.0"
description = "Enables exposing counters for number of slog records per level"
homepage = "https://github.com/facebookexperimental/rust-shed/"
repository = "https://github.com/facebookexperimental/rust-shed/"
readme = "../../README.md"
include = ["src/**/*.rs"]

[dependencies]
stats = { path = "../stats", version = "0.1.0" }
slog = { version = "2.5", features = ["max_level_debug"] }
