[package]
name = "serde_starlark"
edition = "2018"
version = "0.1.0"
authors = ['Facebook', 'Daniel Xu <dlxu@fb.com>']
license = "MIT OR Apache-2.0"
description = "Serde serializer for generating syntactically correct Python code"
homepage = "https://github.com/facebookexperimental/rust-shed/"
repository = "https://github.com/facebookexperimental/rust-shed/"
readme = "../../README.md"
include = ["src/*.rs", "test/starlark_test.rs"]

[lib]
path = "src/lib.rs"

[[bin]]
name = "starlark_test"
path = "test/starlark_test.rs"

[dependencies]
maplit = "1.0"
serde = { version = "1.0", features = ["derive", "rc"] }
