[workspace]

members = [
    "shed/ascii_ext",
    "shed/async_compression",
    "shed/async_unit",
    "shed/bytes_ext",
    "shed/cachelib_stub",
    "shed/chrome_trace",
    "shed/cloned",
    "shed/codegen_includer_proc_macro",
    "shed/failure_ext",
    "shed/fbinit",
    "shed/fbinit/macros",
    "shed/futures_ext",
    "shed/futures_stats",
    "shed/lock_ext",
    "shed/memcache_stub",
    "shed/memcache_stub/common",
    "shed/netstring",
    "shed/panichandler",
    "shed/perthread",
    "shed/scuba_sample",
    "shed/scuba_stub",
    "shed/slog_glog_fmt",
    "shed/sql",
    "shed/sql/common",
    "shed/sql/tests_lib",
    "shed/stats",
    "shed/stats/traits",
    "shed/thrift_compiler",
    "shed/time_ext",
    "shed/tracing",
]
