[workspace]

members = [
    "shed/ascii_ext",
    "shed/async_compression",
    "shed/async_unit",
    "shed/bytes_ext",
    "shed/cached_config",
    "shed/cachelib_stub",
    "shed/chrome_trace",
    "shed/cloned",
    "shed/codegen_includer_proc_macro",
    "shed/failure_ext",
    "shed/fbinit",
    "shed/fbinit/macros",
    "shed/futures_ext",
    "shed/futures_stats",
    "shed/hostname",
    "shed/lock_ext",
    "shed/memcache_stub",
    "shed/memcache_stub/common",
    "shed/netstring",
    "shed/panichandler",
    "shed/perthread",
    "shed/scuba_sample",
    "shed/scuba_stub",
    "shed/secure_utils",
    "shed/serde-starlark",
    "shed/services",
    "shed/services/common",
    "shed/slog_glog_fmt",
    "shed/slog_stats",
    "shed/sorted_vector_map",
    "shed/sql",
    "shed/sql/common",
    "shed/sql/tests_lib",
    "shed/stats",
    "shed/stats/traits",
    "shed/thrift_compiler",
    "shed/time_ext",
    "shed/tracing",
]

[patch.crates-io]
chashmap = { git = "https://gitlab.redox-os.org/ahornby/chashmap", rev = "901ace2ca3cdbc2095adb1af111d211e254e2aae" }
const-random = { git = "https://github.com/fbsource/const-random", rev = "374c5b46427fe2ffbf6acbd9c1687e0f1a809f95" }
gotham = { git = "https://github.com/krallin/gotham.git", branch = "socket_data" }
gotham_derive = { git = "https://github.com/krallin/gotham.git", branch = "socket_data" }
prost = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
prost-build = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
prost-derive = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
prost-types = { git = "https://github.com/gabrielrussoc/prost", branch = "protoc-runtime" }
protobuf-build = { git = "https://github.com/tikv/protobuf-build.git", rev = "1b8b7f8b4aa1be4647acd85bab9345583a5df4f1" }
pyo3 = { git = "https://github.com/PyO3/pyo3.git", rev = "4af61e83c34a04d74679a1048ee3866831a327ab" }
r2d2_sqlite = { git = "https://github.com/jsgf/r2d2-sqlite.git", rev = "6d77a828ca0a3c507a3f58561532a1b6c66c7918" }
rustfilt = { git = "https://github.com/jsgf/rustfilt.git", rev = "8141fa7f1caee562ee8daffb2ddeca3d1f0d36e5" }
tokio-core = { git = "https://github.com/bolinfest/tokio-core", rev = "5f37aa3c627d56ee49154bc851d6930f5ab4398f" }
toml = { git = "https://github.com/jsgf/toml-rs", branch = "master" }
