[package]
name = "memcache"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "MIT OR Apache-2.0"
include = ["src/*.rs"]

[dependencies]
memcache_common = { path = "common", version = "0.1.0" }
