[package]
name = "async_unit"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/lib.rs"]

[dependencies]
futures-preview = { package = "futures", version = "0.3", features = ["async-await", "compat"] }
tokio-compat = "0.1"

[dev-dependencies]
futures = "0.1"
tokio = { version = "=0.2.11", features = ["full"] }
tokio-old = { package = "tokio", version = "0.1" }
tokio-timer = "0.2"
