[package]
name = "tracing"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/**/*.rs"]

[dependencies]
chrome-trace = { path = "../chrome_trace" }
time_ext = { path = "../time_ext" }
futures = "0.1" # todo: rename to "futures-old"
lazy_static = "1.4"
maplit = "1.0"
parking_lot = "0.10"
rand = { version = "0.7", features = ["small_rng"] }
serde_json = "1.0"
tokio = "0.1" # todo: rename to "tokio-old"
uuid = { version = "0.8", features=["v4"] }
