[package]
name = "tracing"
version = "0.1.0"
authors = ["Facebook <opensource+rust-shed@fb.com>"]
edition = "2018"
description = "Stores traces of events viewable in Chrome trace viewer"
readme = "../../README.md"
repository = "https://github.com/facebookexperimental/rust-shed/"
license = "MIT OR Apache-2.0"

[dependencies]
chrome-trace = { path = "../chrome_trace", version = "0.1.0" }
futures = "0.1.30"
lazy_static = "1.0"
maplit = "1.0"
parking_lot = "0.10.2"
rand = { version = "0.7", features = ["small_rng"] }
serde_json = { version = "1.0", features = ["float_roundtrip"] }
time_ext = { path = "../time_ext", version = "0.1.0" }

[dev-dependencies]
tokio = "0.1"
