[package]
name = "services_common"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "MIT OR Apache-2.0"
include = ["**/*.rs"]

[lib]
path = "lib.rs"

[dependencies]
error-chain = "0.12"
