[package]
name = "fbthrift_util"
edition = "2018"
version = "0.1.0"
authors = ['Facebook <opensource+rust-shed@fb.com>']
license = "MIT OR Apache-2.0"
description = "fbthrift extensions utilities"
repository = "https://github.com/facebookexperimental/rust-shed/"
readme = "../../../README.md"
include = ["**/*.rs"]

[lib]
path = "lib.rs"

[dependencies]
tokio = { version = "0.2.25", features = ["full", "test-util"] }
