[package]
name = "fbthrift_util"
edition = "2018"
version = "0.1.0"
authors = ['Facebook', 'Daniel Xu <dlxu@fb.com>']
license = "MIT OR Apache-2.0"
description = "fbthrift extensions utilities"
homepage = "https://github.com/facebookexperimental/rust-shed/"
repository = "https://github.com/facebookexperimental/rust-shed/"
readme = "../../../README.md"
include = ["**/*.rs"]

[lib]
path = "lib.rs"

[dependencies]
tokio = { version = "0.2.24", features = ["full", "test-util"] }
