[package]
name = "sql_tests_lib"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "MIT OR Apache-2.0"
include = ["**/*.rs"]

[lib]
path = "lib.rs"

[dependencies]
sql = { path = "..", version = "0.1.0" }
chrono = { version = "0.4", features = ["serde"] }
futures-old = { package = "futures", version = "0.1.30" }
rand = { version = "0.7", features = ["small_rng"] }
