[package]
name = "cached_config"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/**/*.rs"]

[dependencies]
fbinit = { path = "../fbinit" }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
slog = { version = "2.5", features = ["max_level_debug"] }

[dev-dependencies]
serde_derive = "1.0"
