[package]
name = "stats"
edition = "2018"
version = "0.1.0"
authors = ['Facebook', 'Daniel Xu <dlxu@fb.com>']
license = "MIT OR Apache-2.0"
description = "Stats library"
homepage = "https://github.com/facebookexperimental/rust-shed/"
repository = "https://github.com/facebookexperimental/rust-shed/"
readme = "../../README.md"
include = ["src/**/*.rs"]

[dependencies]
fbinit = { path = "../fbinit", version = "0.1.0" }
futures_ext = { package = "futures_01_ext", path = "../futures_01_ext", version = "0.1.0" }
perthread = { path = "../perthread", version = "0.1.0" }
stats_traits = { path = "traits", version = "0.1.0" }
futures = { version = "0.3.5", features = ["async-await", "compat"] }
futures-old = { package = "futures", version = "0.1.30" }
lazy_static = "1.0"
tokio = { version = "0.2.24", features = ["full", "test-util"] }
tokio-old = { package = "tokio", version = "0.1" }
