[package]
name = "stats"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "GPLv2+"
include = ["src/**/*.rs"]

[dependencies]
fbinit = { path = "../fbinit" }
futures_ext = { path = "../futures_ext" }
perthread = { path = "../perthread" }
stats_traits = { path = "traits" }
auto_impl = { git = "https://github.com/auto-impl-rs/auto_impl", rev = "43ad0ed49f67168b2971b271481e75afac589b24" }
futures = { version = "0.3", features = ["async-await", "compat"] }
futures-old = { package = "futures", version = "0.1" }
lazy_static = "1.0"
tokio = { version = "0.2", features = ["full"] }
tokio-old = { package = "tokio", version = "0.1" }
