[package]
name = "stats"
version = "0.1.0"
authors = ["Facebook <opensource+rust-shed@fb.com>"]
edition = "2018"
description = "Stats library"
readme = "../../README.md"
repository = "https://github.com/facebookexperimental/rust-shed/"
license = "MIT OR Apache-2.0"

[dependencies]
fbinit = { path = "../fbinit", version = "0.1.0" }
futures = { version = "0.3.5", features = ["async-await", "compat"] }
lazy_static = "1.0"
perthread = { path = "../perthread", version = "0.1.0" }
stats_traits = { path = "traits", version = "0.1.0" }
tokio_shim = { path = "../tokio_shim", version = "0.1.0" }

[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util"] }
