[package]
name = "services"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "MIT OR Apache-2.0"
include = ["src/**/*.rs"]

[dependencies]
fbinit = { path = "../fbinit" }
services_common = { path = "common" }
