[package]
name = "services"
version = "0.1.0"
authors = ["Facebook <opensource+rust-shed@fb.com>"]
edition = "2018"
description = "Stubs for facebook services"
readme = "../../README.md"
repository = "https://github.com/facebookexperimental/rust-shed/"
license = "MIT OR Apache-2.0"

[dependencies]
fbinit = { path = "../fbinit", version = "0.1.0" }
services_common = { path = "common", version = "0.1.0" }
