[package]
name = "sql_common"
version = "0.1.0"
authors = ["Facebook <opensource+rust-shed@fb.com>"]
edition = "2018"
description = "Common definitions for sql crate"
readme = "../../../README.md"
repository = "https://github.com/facebookexperimental/rust-shed/"
license = "MIT OR Apache-2.0"

[lib]
path = "lib.rs"

[dependencies]
anyhow = "1.0"
auto_impl = "0.4"
cloned = { path = "../../cloned", version = "0.1.0" }
failure_ext = { path = "../../failure_ext", version = "0.1.0" }
futures = { version = "0.3.5", features = ["async-await", "compat"] }
futures-old = { package = "futures", version = "0.1.30" }
futures-util = "0.3.7"
futures_ext = { package = "futures_01_ext", path = "../../futures_01_ext", version = "0.1.0" }
futures_stats = { path = "../../futures_stats", version = "0.1.0" }
lazy_static = "1.0"
mysql_async = "0.23"
mysql_derive = { path = "../derive", version = "0.1.0" }
rusqlite = { version = "0.23", features = ["blob", "bundled"] }
stats = { path = "../../stats", version = "0.1.0" }
thiserror = "1.0"
time_ext = { path = "../../time_ext", version = "0.1.0" }

[dev-dependencies]
sql = { path = "..", version = "0.1.0" }
sql_tests_lib = { path = "../tests_lib", version = "0.1.0" }
