[package]
name = "mysql_derive"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "MIT OR Apache-2.0"
include = ["*.rs"]

[lib]
path = "lib.rs"
proc-macro = true
test = false
doctest = false

[dependencies]
quote = "1.0"
syn = { version = "1.0", features = ["full", "visit", "visit-mut", "fold", "extra-traits"] }
