[package]
name = "limited_async_read"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "MIT OR Apache-2.0"
include = ["src/**/*.rs"]

[dependencies]
tokio-io = "0.1"

[dev-dependencies]
futures = "0.1"
