[package]
name = "fbthrift_framed"
edition = "2018"
version = "0.1.0"
authors = ['Facebook <opensource+rust-shed@fb.com>']
license = "MIT OR Apache-2.0"
description = "fbthrift extensions for framed transport"
repository = "https://github.com/facebookexperimental/rust-shed/"
readme = "../../../README.md"

[lib]
path = "lib.rs"

[dependencies]
byteorder = "1.3"
bytes = { version = "0.5", features = ["serde"] }
tokio-util = { version = "0.2", features = ["codec", "udp"] }

[dev-dependencies]
futures = { version = "0.3.5", features = ["async-await", "compat"] }
tokio = { version = "0.2.25", features = ["full", "test-util"] }
