[package]
name = "fbthrift_framed"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "MIT OR Apache-2.0"
include = ["**/*.rs"]

[lib]
path = "lib.rs"

[dependencies]
bytes_ext = { path = "../../bytes_ext" }
byteorder = "1.3"
bytes = { version = "0.5", features = ["serde"] }
bytes-old = { package = "bytes", version = "0.4", features = ["serde"] }
tokio-codec = "0.1"
tokio-io = "0.1"
tokio-proto = "0.1"
tokio-util = { version = "0.2", features = ["codec", "udp"] }

[dev-dependencies]
futures = { version = "0.3.5", features = ["async-await", "compat"] }
tokio = { version = "=0.2.13", features = ["full", "test-util"] }
